# Generated by Django 5.2.8 on 2025-12-01 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='excel_files/', verbose_name='Fichier Excel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('entries_count', models.IntegerField(default=0, verbose_name="Nombre d'entrées")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_files', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Fichier Excel',
                'verbose_name_plural': 'Fichiers Excel',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la colonne')),
                ('field_type', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Téléphone'), ('select', 'Liste déroulante'), ('radio', 'Choix unique'), ('checkbox', 'Choix multiples'), ('textarea', 'Zone de texte')], default='text', max_length=20, verbose_name='Type de champ')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Options (pour select, radio, checkbox)')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='api.excelfile', verbose_name='Fichier Excel')),
            ],
            options={
                'verbose_name': 'Colonne Excel',
                'verbose_name_plural': 'Colonnes Excel',
                'ordering': ['order'],
            },
        ),
    ]
