# Generated by Django 5.2.8 on 2025-12-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, unique=True, verbose_name='Nom du fichier')),
                ('name', models.CharField(max_length=255, verbose_name='Nom affiché')),
                ('file_path', models.CharField(max_length=1000, verbose_name='Chemin du fichier')),
                ('sheets_count', models.IntegerField(default=0, verbose_name='Nombre de feuilles')),
                ('sheets_json', models.JSONField(default=list, verbose_name='Liste des feuilles')),
                ('total_entries', models.IntegerField(default=0, verbose_name="Nombre d'entrées")),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Taille du fichier')),
                ('file_modified', models.DateTimeField(verbose_name='Date de modification du fichier')),
                ('cached_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise en cache')),
            ],
            options={
                'verbose_name': 'Cache de fichier',
                'verbose_name_plural': 'Cache des fichiers',
                'ordering': ['-file_modified'],
            },
        ),
    ]
