# Generated by Django 5.2.8 on 2025-12-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_filecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecache',
            name='sheets_details',
            field=models.JSONField(default=dict, verbose_name='Détails des feuilles'),
        ),
    ]
