# Generated by Django 5.2.8 on 2025-12-08 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_filecache_sheets_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255, verbose_name='Nom de la feuille')),
                ('headers', models.JSONField(default=list, verbose_name='En-têtes des colonnes')),
                ('columns_info', models.JSONField(default=list, verbose_name='Infos des colonnes')),
                ('data', models.JSONField(default=list, verbose_name='Données de la feuille')),
                ('rows_count', models.IntegerField(default=0, verbose_name='Nombre de lignes')),
                ('cached_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise en cache')),
                ('file_cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_data', to='api.filecache')),
            ],
            options={
                'verbose_name': 'Cache de feuille',
                'verbose_name_plural': 'Cache des feuilles',
                'unique_together': {('file_cache', 'sheet_name')},
            },
        ),
    ]
