# Generated by Django 5.2.8 on 2025-12-11 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_filecache_last_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filecache',
            name='archived_path',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Chemin d'archive"),
        ),
        migrations.AddField(
            model_name='filecache',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='filecache',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_files', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='filecache',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
    ]
